name: Issue and PR notifications

on:
  issues:
    types: closed
  pull_request:
    types: opened

jobs:
  notify_issue_closed:
    if: github.event.issue.state == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to issue
        uses: peter-evans/add-comment@v1
        with:
          body: 'The issue is now resolved.'

  notify_pr_opened:
    if: github.event.pull_request.number == 1
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: peter-evans/add-comment@v1
        with:
          body: 'Congratulations on opening your first pull request!'
