name: Congratulate on first pull request and comment on closed issue

on:
  pull_request:
    types: [opened]
  issues:
    types: [closed]

jobs:
  congratulate-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the user's first pull request
        uses: jaydson/first-pr-action@v1
        id: first-pr
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Congratulate user on first pull request
        if: steps.first-pr.outputs.first_pr == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const author = context.payload.pull_request.user.login;
            const comment = 'Congratulations on opening your first pull request! :tada:';
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });
      - name: Check if issue is closed
        if: github.event.issue.state == 'closed'
        run: echo "Issue is closed"
      - name: Comment on issue
        uses: actions/github-script@v5
        if: github.event.issue.state == 'closed'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = 'The issue is now resolved.';
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: comment
            });
