name: Issue and PR notifications

on:
  issues:
    types: closed
  pull_request:
    types: opened

jobs:
  notify_issue_closed:
    if: github.event.issue.state == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The issue is now resolved.'
            })

  notify_pr_opened:
    if: github.event.pull_request.number != null
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Congratulations on opening your pull request!'
            })
